[sod]
name = "Coast of Sod"
anchor_position = [233, 35]
fertility = 0.03
maximal_garrison = 8

[annar]
name = "Taiga of Annar"
anchor_position = [220, 66]
fertility = 0.05
garrison = 4
maximal_garrison = 17